# Numpy
    (1) Numpy is numerical python library. It is used to work with arrays
    (2) we can perform mathematical operations on array and get results in fraction of sec
    (3) we can import a numpy module by using "import numpy" keyword
    (4) syntax: import numpy as np

In [1]:
import numpy as np

# Converting list into array:

In [1]:
import numpy as np
a = [1, 2, 3, 4, 5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [2]:
print(b)
print(b+10)
print(np.log(b))
print(np.log(a))

[1 2 3 4 5]
[11 12 13 14 15]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


# converting array to list:

In [3]:
b.tolist()

[1, 2, 3, 4, 5]

In [4]:
print(b.tolist())

[1, 2, 3, 4, 5]


# Addition of two arrays:

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a+b)

[ 6  8 10 12]


# Types of numpy arrays:
    Numpy arrays are classified into 3 types:
        (1) 0-Dimensional array
        (2) 1-Dimensional array
        (3) 2-Dimensional array

# 0-Dimensional array:
    All the fundamental data type holds single value, if we convert them to numpy then they become 0-Dimensional array

In [6]:
a = 10
print(a)
print(type(a))

10
<class 'int'>


In [7]:
a = 10
b = np.array(a)
print(b)
print(type(b))

10
<class 'numpy.ndarray'>


In [8]:
print(f"dim :{b.ndim}")
print(f"shape:{b.shape}")

dim :0
shape:()


# 1-Dimensional array:
    All the collection data type holds multiple values, if we convert them to numpy then they become 1-Dimensional array

In [9]:
a = [1, 2, 3, 4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
print(f"dim :{b.ndim}")
print(f"shape:{b.shape}")

dim :1
shape:(4,)


# 2-Dimensional array:
    All the collection data types with nested CDT of same length, then if we convert them to numpy then they become 2-Dimensional array

In [11]:
a = [[1, 2], [3, 4], [5, 6]]
b = np.array(a)
print(b)
print(type(b))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [12]:
print(f"dim :{b.ndim}")
print(f"shape:{b.shape}")

dim :2
shape:(3, 2)


# 1-Dimensional array:
    we can create 1-Dimensional array by mulitple ways:
    (1) arrange(start,end,step)                 : It is array-valued version of built-in python range function
    (2) linspace(start,end, numberofsample)     : It returns evenly spaced numbers over a interval
    (3) zeros(shape of array,dtype=float)       : It returns array of zeros of different dimension based on given shape
    (4) ones(shape of array,dtype=float)        : It returns array of ones of different dimension based on given shape
    (5) random.randint(start,end,numberofsample): It returns array of random numbers with the given number of samples

In [14]:
arr_1 = np.arange(1,10,1)
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr_1 = np.linspace(1,10,5)
arr_1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# point to remember:
    sample = (end - start)/(no of samples - 1)

In [17]:
arr_1 = np.zeros((5,), dtype = int)
arr_1

array([0, 0, 0, 0, 0])

In [18]:
arr_1 = np.ones((5,), dtype = 'int')
arr_1

array([1, 1, 1, 1, 1])

In [19]:
arr_1 = np.random.randint(1,10,5)
arr_1

array([9, 2, 7, 8, 5])

# Accessing the elements of array:
    We can access the elements of the array by four ways:
    (1) Accessing the single element by indexing  
    (2) Accessing the multiple element by slicing    
    (3) Accessing the multiple element by indexing    
    (4) Accessing the multiple elements by condition(fancy indexing or mask indexing)

In [20]:
a = np.array([100, 120, 130, 190, 200, 14, 18, 26])
print(a)
print(a[1])
print(a[-1])

[100 120 130 190 200  14  18  26]
120
26


In [21]:
print(a[0:5:2])

[100 130 200]


In [23]:
# array[list of index number]
print(a[[1, 2, 3]])

[120 130 190]


In [24]:
# array[condition]
a = np.array([45, 46, 47])
print(a)

[45 46 47]


In [25]:
a>=46

array([False,  True,  True])

In [26]:
print(a[a>=46])

[46 47]


# Modifying an array:

# Adding elements into array:
    syntax(1): np.append(array, element)
    syntax(2): np.append(array, [elements])

In [27]:
a = np.array([45, 46,47])
b =np.append(a,110)
print(b)

[ 45  46  47 110]


In [28]:
a = np.array([45, 46,47])
b =np.append(a,[140,120,130])
print(b)

[ 45  46  47 140 120 130]


# Replacing elements of array
    syntax(1): array[index] = value
    syntax(2): array[[index numbers]] = value
    syntax(3): array[[index numbers]] = [values]

In [29]:
arr_1    = np.array([45, 46, 47])
arr_1[1] = 100
arr_1

array([ 45, 100,  47])

In [30]:
arr_1    = np.array([45, 46, 47])
arr_1[[1, 2]] = 15
arr_1

array([45, 15, 15])

In [31]:
arr_1    = np.array([45, 46, 47])
arr_1[[1, 2]] = [150, 200]
arr_1

array([ 45, 150, 200])

# Deleting element of array:
    syntax(1): np.delete(array, index number)
    syntax(2): np.delete(array, [index numbers])

In [32]:
arr_1 = np.array([1, 2, 3, 4])
arr   = np.delete(arr_1, 1)
arr

array([1, 3, 4])

In [33]:
arr_1 = np.array([1, 2, 3, 4])
arr   = np.delete(arr_1, [1, 2])
arr

array([1, 4])

# copying an array:

In [35]:
arr    = np.array([1, 2, 3])
brr    = arr.copy()
brr[0] = 100
print(arr)
print(brr)

[1 2 3]
[100   2   3]


# Sorting an array:

In [36]:
arr = np.array([4, 6, 8, 2, 1])
brr = np.sort(arr)
print(arr)
print(brr)

[4 6 8 2 1]
[1 2 4 6 8]


# Operation on array:

In [37]:
arr = np.array([1, 2, 3, 4])
brr = arr+1
print(brr)
crr = arr+0
print(crr)
drr = arr**2
print(drr)
print(arr+brr)
print(arr-brr)

[2 3 4 5]
[1 2 3 4]
[ 1  4  9 16]
[3 5 7 9]
[-1 -1 -1 -1]


# comparision operator:

In [38]:
print(arr == brr)
print(brr >= arr)
print(np.array_equal(arr,brr))
print(np.array_equal(arr,crr))

[False False False False]
[ True  True  True  True]
False
True


# mathematical operations:

In [39]:
arr = np.array([0, 1, 2, 3, 4])
print(np.log(arr))
print(np.sin(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


C:\Users\ANANTH\AppData\Local\Temp\ipykernel_4144\1510414748.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [40]:
import warnings
warnings.simplefilter("ignore")

In [41]:
arr = np.array([0, 1, 2, 3, 4])
print(np.log(arr))
print(np.sin(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


# 2-Dimensional array:
    we can create 2-Dimensional array by multiple ways:
    (1) np.zeros(shape of array, dtype)
    (2) np.ones(shape of array, dtype)
    (3) np.eye(row, column)
    (4) np.diag(1d array)
    (5) np.diag(2d array)

In [42]:
l = [[1,2], [10,20], [34,45], [1,9]]
a = np.array(l)
a

array([[ 1,  2],
       [10, 20],
       [34, 45],
       [ 1,  9]])

In [43]:
print(a)

[[ 1  2]
 [10 20]
 [34 45]
 [ 1  9]]


In [44]:
l = [[0,1,2,5],[2,3,4,5]]
b = np.array(l)
b

array([[0, 1, 2, 5],
       [2, 3, 4, 5]])

In [45]:
print(len(b[0]))
print(b.ndim)
print(b.shape)

4
2
(2, 4)


In [46]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
print(np.zeros((3,3), dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [48]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
print(np.ones((3,3), dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [50]:
print(np.eye(2,2))

[[1. 0.]
 [0. 1.]]


In [51]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
print(np.diag([1, 2]))

[[1 0]
 [0 2]]


In [54]:
print(np.diag([1, 2, 3, 4, 5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [55]:
print(np.diag([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

[1 5 9]


# Accessing the elements of 2-Dimension array:
    we can access the element of array by multiple ways:
    syntax(1): array[row index, column index]
    synatx(2): array[row index]
    syntax(3): array[start row index : end row index]

In [56]:
arr = np.array([[10,20,50],[30,40,60],[70,80,90]])
print(arr)

[[10 20 50]
 [30 40 60]
 [70 80 90]]


In [57]:
arr[0,0]

10

In [58]:
arr[1, 2]

60

In [59]:
arr[1]

array([30, 40, 60])

In [60]:
arr[1:3]

array([[30, 40, 60],
       [70, 80, 90]])

# Modifying the elements of 2D-array:
    we can modify the value of array by multiple ways:
    syntax(1): array[row index, column index] = value
    syntax(2): array[row index] = list of elements depend on the row

In [61]:
arr = np.array([[10,20,50],[30,40,60],[70,80,90]])
print(arr)

[[10 20 50]
 [30 40 60]
 [70 80 90]]


In [62]:
arr[1,0] = 95
arr

array([[10, 20, 50],
       [95, 40, 60],
       [70, 80, 90]])

In [63]:
arr[1] = [25, 35, 55]
arr

array([[10, 20, 50],
       [25, 35, 55],
       [70, 80, 90]])

# Flattening: 
    converting a nd array to 1D array.
    syntax: array.ravel()

In [65]:
arr = np.array([[0,1,2],[3,4,5]])
print(arr.ravel())

[0 1 2 3 4 5]


In [2]:
import numpy as np
arr = np.array([[0,1,2],[3,4,5]])
print(arr.shape)
print(arr.ravel().shape)

(2, 3)
(6,)


# Reshape of array:
    (1) It will convert one shape of array into other
    (2) firstly, It will convert any shape into 1D then converts to other shape depends on fesability

In [66]:
arr = np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [67]:
brr = arr.reshape(6,1)
print(brr)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [69]:
arr = np.array([[0,1,5],[10,50,8]])
print(arr)

[[ 0  1  5]
 [10 50  8]]


In [70]:
print(arr.shape)

(2, 3)


In [71]:
print(arr.reshape(3,2))

[[ 0  1]
 [ 5 10]
 [50  8]]


# Transpose of array:

In [72]:
crr = arr.T
print(crr)

[[ 0 10]
 [ 1 50]
 [ 5  8]]


# Sorting 2D array:
    Here, axis=0(column wise) and axis=1(row wise)

In [73]:
arr = np.array([1,4,2,8,3,5,9])
brr = np.sort(arr)
print(brr)

[1 2 3 4 5 8 9]


In [75]:
arr = np.array([[5, 4, 6], [2, 8, 2],[8, 9, 20]])
print(np.sort(arr, axis=0))

[[ 2  4  2]
 [ 5  8  6]
 [ 8  9 20]]


In [76]:
print(np.sort(arr, axis=1))

[[ 4  5  6]
 [ 2  2  8]
 [ 8  9 20]]


# operation on 2D array:
    To perform any kind of operation both the shapes of array should be same

In [78]:
arr = np.array([[1,2],[3,4],[5,6]])
brr = np.array([[40,4],[14,24],[34,44]])
print(arr+brr)

[[41  6]
 [17 28]
 [39 50]]


In [80]:
arr = np.array([[1,2],[3,4]])
brr = np.array([[5,6],[7,8]])
print(arr*brr)

[[ 5 12]
 [21 32]]


In [81]:
arr = np.array([[1,2],[3,4]])
brr = np.array([[5,6],[7,8]])
crr = np.matmul(arr, brr)
print(crr)

[[19 22]
 [43 50]]


# concatenate 2D array:

In [82]:
arr = np.array([[1,2],[3,4]])
brr = np.array([[5,6],[7,8]])

In [83]:
print(np.concatenate((arr,brr), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
print(np.vstack((arr,brr)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [85]:
print(np.concatenate((arr,brr), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [86]:
print(np.hstack((arr,brr)))

[[1 2 5 6]
 [3 4 7 8]]
